# Copyright (c) 2024 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

# GitHub Actions workflow to deploy the Web PoP Miner to the staging environment.
name: "Staging"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: "staging-deploy-${{ github.event.number || github.ref }}"
  cancel-in-progress: false

jobs:
  # Build and push Docker image
  docker:
    name: "Docker"
    uses: hemilabs/actions/.github/workflows/docker.yml@main
    permissions:
      contents: read
      packages: write # Needed to push to the GitHub Container Registry
    with:
      version: "${{ github.sha }}"
      context: "."
      file: "./Dockerfile"
      dockerhub: true
      tags: |
        hemilabs/popm-web:${{ github.sha }}
        ghcr.io/hemilabs/popm-web:${{ github.sha }}
    secrets:
      DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
      DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_TOKEN }}"

  # Deploy to Kubernetes cluster
  deploy:
    name: "Deploy to staging"
    uses: hemilabs/actions/.github/workflows/deploy-kustomize.yml@main
    needs: [ "docker" ]
    permissions:
      contents: read
    with:
      namespace: "popm-web"
      kustomize: "./kubernetes/kustomize/overlays/staging/"
      image: "hemilabs/popm-web:${{ github.sha }}"
      environment-name: "staging"
      preapply: |
        sed -i -e 's/HEMI_STAGING_DOMAIN/${{ vars.HEMI_DOMAIN_STAGING }}/g' staging-patch.yaml
    secrets:
      KUBECONFIG: "${{ secrets.VKE_STAGING_KUBECONFIG }}"
      KUBECONFIG_CONTEXT: "${{ secrets.VKE_STAGING_KUBECONFIG_CONTEXT }}"
