# Copyright (c) 2024 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

# GitHub Actions workflow to deploy the Web PoP Miner to the testnet prod environment.
name: "Testnet"
on:
  push:
    tags: [ "v*.*.*" ]

concurrency:
  group: "testnet-deploy-${{ github.event.number || github.ref }}"
  cancel-in-progress: false

jobs:
  # Prepare to deploy and release
  prepare:
    name: "Prepare"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    outputs:
      version: "${{ steps.data.outputs.version }}"
      tag: "${{ steps.data.outputs.tag }}"
      version_type: "${{ steps.version.outputs.type }}"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: "Retrieve build data"
        id: "data"
        run: |
          VERSION=$(echo "$RAW_VERSION" | sed -e 's/^v//')
          TAG=$(echo "$RAW_VERSION" | sed -E 's/^([^v])/v\1/g')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          
          TYPE=unstable
          if echo "$VERSION" | grep -Eq '^[1-9][0-9]*\.[0-9]+\.[0-9]+$'; then
            TYPE=stable
          fi
          echo "Detected that $TAG is $TYPE"
          echo "type=$TYPE" >> "$GITHUB_OUTPUT"

  # Build and push Docker image
  docker:
    name: "Docker"
    uses: hemilabs/actions/.github/workflows/docker.yml@main
    needs: [ "prepare" ]
    permissions:
      contents: read
      packages: write # Needed to push to the GitHub Container Registry
    with:
      version: "${{ needs.prepare.outputs.version }}"
      context: "."
      file: "./Dockerfile"
      dockerhub: true
      tags: |
        hemilabs/popm-web:latest
        hemilabs/popm-web:${{ needs.prepare.outputs.tag }}
        hemilabs/popm-web:${{ github.sha }}
        ghcr.io/hemilabs/popm-web:latest
        ghcr.io/hemilabs/popm-web:${{ needs.prepare.outputs.tag }}
        ghcr.io/hemilabs/popm-web:${{ github.sha }}
    secrets:
      DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
      DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_TOKEN }}"

  # Deploy to Kubernetes cluster
  deploy:
    name: "Deploy to testnet"
    uses: hemilabs/actions/.github/workflows/deploy-kustomize.yml@main
    needs: [ "prepare", "docker" ]
    permissions:
      contents: read
    with:
      namespace: "popm-web"
      kustomize: "./kubernetes/kustomize/overlays/testnet/"
      image: "hemilabs/app:${{ needs.prepare.outputs.tag }}"
      environment-name: "testnet"
      environment-url: "https://pop-miner.hemi.xyz/"
    secrets:
      KUBECONFIG: "${{ secrets.VKE_TESTNET_KUBECONFIG }}"
      KUBECONFIG_CONTEXT: "${{ secrets.VKE_TESTNET_KUBECONFIG_CONTEXT }}"
